src/BlogBundle/Entity/Category.php
<?php

namespace BlogBundle\Entity;

/**
 * Category
 */
class Category
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $name;

    public function __toString()
    {
        return $this->name;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Category
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @var string
     */
    private $description;

    protected $entry;

    public function __construct()
    {
        $this->entry = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Category
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    public function getEntries()
    {
        return $this->entry;
    }

    /**
     * Add entry
     *
     * @param \BlogBundle\Entity\Entry $entry
     *
     * @return Category
     */
    public function addEntry(\BlogBundle\Entity\Entry $entry)
    {
        $this->entry[] = $entry;

        return $this;
    }

    /**
     * Remove entry
     *
     * @param \BlogBundle\Entity\Entry $entry
     */
    public function removeEntry(\BlogBundle\Entity\Entry $entry)
    {
        $this->entry->removeElement($entry);
    }

    /**
     * Get entry
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getEntry()
    {
        return $this->entry;
    }
}

src/BlogBundle/Form/CategoryType.php
<?php

namespace BlogBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class CategoryType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('name', TextType::class, array("label"=>"Nombre", "required"=>"required", "attr"=>array(
            "class" => "form-name form-control")))
            ->add('description', TextareaType::class, array("label"=>"Descripción", "required"=>"required", "attr"=>array(
                "class"=>"form-description form-control")))
            ->add('Guardar', SubmitType::class, array("attr"=>array(
                "class" => "form-submit btn btn-success")));
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'BlogBundle\Entity\Category'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'blogbundle_category';
    }


}

src/BlogBundle/Controller/CategoryController.php
<?php

namespace BlogBundle\Controller;

use BlogBundle\Entity\Category;
use BlogBundle\Entity\Tag;
use BlogBundle\Form\CategoryType;
use BlogBundle\Form\TagType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\Session;

class CategoryController extends Controller
{
    private $session;

    public function __construct(){
        $this->session = new Session();
    }

    public function indexAction(){
        $em = $this->getDoctrine()->getManager();
        $categories_repository = $em->getRepository("BlogBundle:Category");
        $categories = $categories_repository->findAll();
        return $this->render("BlogBundle:Category:index.html.twig", array(
            "categories" => $categories
        ));
    }

    public function addAction(Request $request){
        $category = new Category();

        $form = $this->createForm(CategoryType::class, $category);

        $form->handleRequest($request);

        if($form->isSubmitted()){
            if($form->isValid()){
                $em = $this->getDoctrine()->getManager();
                $category = new Category();
                $category->setName($form->get("name")->getData());
                $category->setDescription($form->get("description")->getData());
                $em->persist($category);
                $flush = $em->flush();
                if($flush == null){
                    $status = true;
                }else{
                    $status = false;
                }
            }else{
                $status = false;
            }
            $this->session->getFlashBag()->add("status", $status);
            return $this->redirectToRoute("blog_index_category");
        }
        return $this->render("BlogBundle:Category:add.html.twig", array(
            "form" => $form->createView()
        ));
    }

    public function deleteAction($id){
        $em = $this->getDoctrine()->getManager();
        $category_repository = $em->getRepository("BlogBundle:Category");
        $category = $category_repository->find($id);
        if(count($category->getEntries()) == 0){
            $em->remove($category);
            $em->flush();
        }
        return $this->redirectToRoute("blog_index_category");
    }

    public function editAction($id, Request $request){
        $em = $this->getDoctrine()->getManager();
        $category_repository = $em->getRepository("BlogBundle:Category");
        $category = $category_repository->find($id);

        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);
        if($form->isSubmitted()){
            if($form->isValid()){
                $category->setName($form->get("name")->getData());
                $category->setDescription($form->get("description")->getData());
                $em->persist($category);
                $flush = $em->flush();
                if($flush == null){
                    $status = true;
                }else{
                    $status = false;
                }
            }else{
                $status = false;
            }
            $this->session->getFlashBag()->add("status", $status);
            return $this->redirectToRoute("blog_index_category");
        }
        return $this->render("BlogBundle:Category:edit.html.twig", array(
            "form" => $form->createView()
        ));
    }
}

src/BlogBundle/Resources/views/Category/add.html.twig
{% extends "BlogBundle::layout.html.twig" %}

{% block content %}
    <div class="col-lg-6">
        <h2>Añadir Categorías</h2>
        {{ form_start(form) }}
        {{ form_end(form) }}
    </div>
    <div class="clearfix"></div>
{% endblock %}

src/BlogBundle/Resources/views/Category/edit.html.twig
{% extends "BlogBundle::layout.html.twig" %}

{% block content %}
    <div class="col-lg-6">
        <h2>Editar Categoría</h2>
        {{ form_start(form) }}
        {{ form_end(form) }}
    </div>
    <div class="clearfix"></div>
{% endblock %}

src/BlogBundle/Resources/views/Category/index.html.twig
{% extends "BlogBundle::layout.html.twig" %}

{% block content %}
    <div class="col-lg-6">
        <h2>Todas las categorías</h2>
        <hr>
        <a href="{{ path("blog_add_category") }} " class="btn btn-success">Anadir categoría</a>
        <hr>
        {% for message in app.session.flashbag().get('status') %}
            {% if message %}
                <div class="alert alert-success">La categoría se ha creado correctamente</div>
            {% else %}
                <div class="alert alert-danger">La categoría no se ha creado, porque el formulario no es válido</div>
            {% endif %}
        {% endfor %}
        <table class="table table-bordered">
            <tr>
                <th>Nombre</th>
                <th>Descripción</th>
                <th>Editar</th>
                <th>Eliminar</th>
            </tr>
            {% for category in categories %}
                <tr>
                    <td>{{ category.name }} </td>
                    <td>{{ category.description }}</td>
                    <td>
                        <a href="{{ path('blog_edit_category', {"id":category.id}) }}" class="btn btn-primary">Editar</a>
                    </td>
                    <td>
                        {% if category.entries|length == 0 %}
                            <a href="{{ path('blog_delete_category', {"id":category.id}) }}" class="btn btn-danger">Eliminar</a>
                        {% else %}
                            <div class="alert alert-warning">Categoría en uso</div>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="clearfix"></div>
{% endblock %}

src/BlogBundle/Resources/views/Category/menu.categories.html.twig
{% for category in categories %}
    <li><a href="#">{{ category.name }}</a></li>
{% endfor %}